# Generated by Django 6.0 on 2026-01-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_flight_hotel_offer_outbound_flight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='beds_description',
            field=models.CharField(blank=True, help_text='Np. 1x double + 2x single / 1x double + sofa', max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='has_air_conditioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='max_occupancy',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='size_m2',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='view_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
