# Generated by Django 6.0 on 2026-01-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_room_beds_description_room_has_air_conditioning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='carrier',
            field=models.CharField(max_length=80),
        ),
    ]
