# Generated by Django 6.0 on 2026-01-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_flight_price_per_person_alter_flight_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offers.room'),
        ),
    ]
