# Generated by Django 6.0 on 2026-01-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_mealplan_hotel_meal_plans_offer_meal_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='meal_plan',
            field=models.CharField(blank=True, choices=[('RO', 'Room only (bez wyżywienia)'), ('BB', 'BB (śniadania)'), ('HB', 'HB (śniadania i obiadokolacje)'), ('FB', 'FB (3 posiłki)'), ('AI', 'All inclusive')], default='', max_length=2),
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='meal_plans',
        ),
        migrations.AddField(
            model_name='hotel',
            name='available_meals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
