# Generated by Django 6.0 on 2026-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_offer_meal_plan_remove_hotel_meal_plans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds_description',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
